### ISSUE TITLE
CPU load is rising with many shows/episodes

### ISSUE THREAD

**Issue by christianvaes** [tomreinartz90/Sonarr-extention-chrome#2]
When sonarr contains many episodes(reddit forum reports talk about 1719 and 1350 episodes and 131 shows) the extension start eating cpu and sometimes also the loading bar keeps spinning.

**Comment by delphiactual** [comment]
153 series, 8642 episodes
Sonarr Connect: (on load)
26K Ram
0-2 CPU

So I'm not seeing this problem...

**Comment by christianvaes** [comment]
That's quite a good use case:) Atleast the number of shows don't seem the problem.

I'm also not sure if the problem still exists, the user who reported this was running Chrom Beta 41 on a MAC. We will keep this bug open for a little while and if no furhter reports will come up it can be closed.

**Comment by tomreinartz90** [comment]
Issue seems to be fixed in version 1.4.
