### ISSUE TITLE
Option button in plugin not working without correct options

### ISSUE THREAD

**Issue by christianvaes** [tomreinartz90/Sonarr-extention-chrome#3]
When you first start the plugin without configuring the correct options, the options button in the extension doesn't work. After the extension is configured correctly through right click on extension --> options it works fine.

**Comment by tomreinartz90** [comment]
Fixed in version 1.4

**Comment by christianvaes** [comment]
This is solved now, but we also improved this by automatically opening the options window incase the configuration is not set.
